### ISSUE TITLE
Priest Talent: Spirit Tap

### ISSUE THREAD

**Issue by Gunn13** [The-Barrens-org/Bugtracker#19] opened 2018-08-05 04:09 UTC
Priest Talent: Spirit Tap

Current behaviour: Does not work at all once 5 points are spent into the talent. (Does in fact work if you have 1-4 points only in the talent)

Expected behaviour: 5 points should make spirit tap proc 100% of the time with killing blow of xp or honor kill.

Steps to reproduce the problem: Put 5 points into spirit tap talent and kill a mob that gives xp.

Include relaible sources for its behaviour: see in game tooltip of the talent.

**Comment by Cheelout** [comment] 2018-08-05 04:27
User signed in and out - now fixed.
Other users verified it is working too.

**Comment by Tamosheik** [comment] 2018-08-08 07:52
I've actually noticed this unexpected behaviour also, so I wouldn't write it off as "working as intended" just yet.
Steps to reproduce behaviour:
1. 'Tag' mob with priest
2.  Kill mob with another character

When this occurs spirit tap does not appear to proc. I expect the proc only occurs if the priest lands the killing blow, although I believe this is incorrect.

Unfortunately my priest is so thoroughly undergeared I can't test the hypothesis on a mob that gives xp.

**Comment by Gunn13** [comment] 2018-08-08 08:34
Would like to clarify, I did not fix this by simply signing in and out.
I cannot confirm why it stopped or why it started again, but it was NOT signing in/out OR clearing the WDB cache files.

Also, it is NORMAL that you do NOT get the buff unless you land the killing blow.

**Closed** 2018-08-16 22:48 UTC
Labels: duplicate/invalid/wont fix
